name: Run Tests on PR

on:
  pull_request:
    branches: [main, master, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: Trigger Vercel Deploy
        if: success()
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/QmYourHookURLHere"
